
export const RECIPE_LIST_REQUEST= 'RECIPE_LIST_REQUEST'
export const RECIPE_LIST_SUCCESS= 'RECIPE_LIST_SUCCESS'
export const RECIPE_LIST_FAIL= 'RECIPE_LIST_FAIL'

export const RECIPE_ADD_REQUEST= 'RECIPE_ADD_REQUEST'
export const RECIPE_ADD_SUCCESS= 'RECIPE_ADD_SUCCESS'
export const RECIPE_ADD_FAIL= 'RECIPE_ADD_FAIL'



export const MY_RECIPE_LIST_REQUEST= 'MY_RECIPE_LIST_REQUEST'
export const MY_RECIPE_LIST_SUCCESS= 'MY_RECIPE_LIST_SUCCESS'
export const MY_RECIPE_LIST_FAIL= 'MY_RECIPE_LIST_FAIL'



export const GET_RECIPE_REQUEST= 'GET_RECIPE_REQUEST'
export const GET_RECIPE_SUCCESS= 'GET_RECIPE_SUCCESS'
export const GET_RECIPE_FAIL= 'GET_RECIPE_FAIL'


export const EDIT_RECIPE_REQUEST= 'EDIT_RECIPE_REQUEST'
export const EDIT_RECIPE_SUCCESS= 'EDIT_RECIPE_SUCCESS'
export const EDIT_RECIPE_FAIL= 'EDIT_RECIPE_FAIL'


export const DELETE_RECIPE_REQUEST= 'DELETE_RECIPE_REQUEST'
export const DELETE_RECIPE_SUCCESS= 'DELETE_RECIPE_SUCCESS'
export const DELETE_RECIPE_FAIL= 'DELETE_RECIPE_FAIL'