export const USER_LOGIN_REQUEST = 'CONST_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'CONST_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'CONST_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'CONST_LOGIN_LOGOUT'