export const USER_LOGIN_REQUEST = 'CONST_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'CONST_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'CONST_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'CONST_LOGIN_LOGOUT'




export const USER_REGISTER_REQUEST = 'CONST_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'CONST_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'CONST_REGISTER_FAIL'





export const BASE_URL = "http://127.0.0.1:5000"